#!/bin/bash
FILE_PATH=$(readlink -f "$0")
FILE_DIR=$(dirname "$FILE_PATH")
APP_PATH=$FILE_DIR/current
PID_FILE=$FILE_DIR/shared/tmp/pids/unicorn.pid

function init_unicorn {
  cd $APP_PATH
  bundle exec unicorn -c $APP_PATH/config/unicorn.rb -E production -D
}
function start_unicorn {
  if [ -f $PID_FILE ] ; then
    read PID < $PID_FILE
    if [ -d /proc/${PID} ] ; then
      echo "Process already running"
    else
      rm $PID_FILE
      init_unicorn
    fi
  else
    init_unicorn
  fi
}
function kill_unicorn {
  if [ -f $PID_FILE ] ; then
    read PID < $PID_FILE
    if [ -d /proc/${PID} ] ; then
      kill $PID
      rm $PID_FILE
    else
      rm $PID_FILE
    fi
  fi
}

if [ $# -ne 1 ]; then
  echo "Invalid Parameters"
else
  if [ "$1" == "off" ]; then
    kill_unicorn
  elif [ "$1" == "on" ]; then
    start_unicorn
  elif [ "$1" == "restart" ]; then
    kill_unicorn
    start_unicorn
  else
    echo "Invalid parameters"
  fi
fi

